### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by eshasadia** [chandlerbing65nm/Pan-Cancer-Nuclei-Instance-Segmentation#2]
Hi Chandler, 
Kaggle links shared by you aren't active. Can u plese check?

**Comment by chandlerbing65nm** [comment]
@eshasadia which one. I'm searching for it now.

**Comment by chandlerbing65nm** [comment]
@eshasadia I found [Pan-Cancer Nuclei Instance Segmentation - #2](https://www.kaggle.com/code/chandlertimm/pan-cancer-nuclei-instance-segmentation-2/notebook) was broken. It is working now, kindly check again. 

If there are other broken links, pls feel free to notify me here. Thanks!
