### ISSUE TITLE
PanNuke Training on Mask R-CNN Json Image not found error

### ISSUE THREAD

**Issue by eshasadia** [chandlerbing65nm/Pan-Cancer-Nuclei-Instance-Segmentation#3]
Hi, 
while training on pannuke json files it's giving image not found error on some random images.
![image](https://user-images.githubusercontent.com/45667822/171427885-466808fd-1f82-4410-a21d-0b51742940b7.png)

**Comment by chandlerbing65nm** [comment]
I re-run the [Pan-Cancer Nuclei Instance Segmentation - #2](https://www.kaggle.com/code/chandlertimm/pan-cancer-nuclei-instance-segmentation-2/edit/run/95083369) notebook, it works fine. 

![image](https://user-images.githubusercontent.com/62779617/171437402-ff298652-ef99-4251-ba01-ef7c4670a750.png)

Did you click copy&edit in my kaggle notebook?

**Comment by chandlerbing65nm** [comment]
oh, you are running it in colab? I've never tried it in colab so I would not know the environment or packages installed there.

**Comment by eshasadia** [comment]
Hi Chandler,
Thankyou for your reply.
Just checked, it's working for kaggle.
